### ISSUE TITLE
blog link broken

### ISSUE THREAD

**Issue by Nishchit14** [pavelsaman/pavelsaman.github.io#1]
Hello Pavel, I have noticed that your blog link is miss-written. `,` was placed instead of `.` mistakenly.

Expected: 
`https://pavelsaman.github.io/`

Current:
![image](https://user-images.githubusercontent.com/5078921/73151484-56749b80-40f1-11ea-8ace-bf94bfa53c88.png)

**Comment by pavelsaman** [comment]
Hi, @Nishchit14 

thank you for pointing it out. I have only found out you've added this issue here :)
